from typing import NewType, Tuple, Union

type Year = int
type Month = int
type Day = Union[int, float]
type Hour = int
type Minutes = int
type Seconds = float
type JulianDate = float
Date = NewType('Date', Tuple[Year, Month, Day])
Time = NewType('Time', Tuple[Hour, Minutes, Seconds])
FullDate = NewType('FullDate', Tuple[Date, Time])
type DecimalTime = float
type Epoch = float
type Angle = int
Degrees = NewType('Degrees', Tuple[Angle, Minutes, Seconds])
type RightAscension = Time
type DecimalDegrees = float
type Declination = Degrees
type HourAngle = Union[Time, Degrees]
type Longitude = Union[Degrees, DecimalDegrees, Angle]
type Latitude =  Union[Degrees, DecimalDegrees, Angle]
type Azimuth = Degrees
type Altitude = Degrees
GeographicCoordinates = NewType('GeographicCoordinates', Tuple[Latitude, Longitude])
HorizontalCoordinates = NewType('HorizontalCoordinates', Tuple[Altitude, Azimuth])
EquatorialCoordinatesHourAngle = NewType('EquatorialCoordinatesHourAngle', Tuple[HourAngle, Declination])
EquatorialCoordinatesRightAscension = NewType('EquatorialCoordinatesRightAscension', Tuple[RightAscension, Declination])
EclipticCoordinates = NewType('EclipticCoordinates', Tuple[Latitude, Longitude])
type Obliquity = DecimalDegrees